# Generated by Django 2.2.8 on 2020-05-15 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classification',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='classification',
            new_name='topic',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ceb69284-178b-403c-bfec-832a32e6eba9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
